doc-warnings: no
test-warnings: no
strictness: high
max-line-length: 79
uses:
    - django
autodetect: yes
ignore-paths:
    - secureauth/migrations
    - secureauth/south_migrations
    - secureauth/management
    - demo
pylint:
  disable:
    - unused-argument
    - model-missing-unicode
